# Generated by Django 6.0.6 on 2026-06-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(unique=True)),
                ('school', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=1)),
                ('famsize', models.CharField(max_length=5)),
                ('Pstatus', models.CharField(max_length=1)),
                ('Medu', models.PositiveIntegerField()),
                ('Fedu', models.PositiveIntegerField()),
                ('Mjob', models.CharField(max_length=30)),
                ('Fjob', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=30)),
                ('guardian', models.CharField(max_length=30)),
                ('traveltime', models.PositiveIntegerField()),
                ('studytime', models.PositiveIntegerField(db_index=True)),
                ('failures', models.PositiveIntegerField()),
                ('schoolsup', models.BooleanField()),
                ('famsup', models.BooleanField()),
                ('paid', models.BooleanField()),
                ('activities', models.BooleanField()),
                ('nursery', models.BooleanField()),
                ('higher', models.BooleanField()),
                ('internet', models.BooleanField()),
                ('romantic', models.BooleanField()),
                ('famrel', models.PositiveIntegerField()),
                ('freetime', models.PositiveIntegerField()),
                ('goout', models.PositiveIntegerField()),
                ('Dalc', models.PositiveIntegerField()),
                ('Walc', models.PositiveIntegerField()),
                ('health', models.PositiveIntegerField()),
                ('absences', models.PositiveIntegerField()),
                ('G1', models.PositiveIntegerField()),
                ('G2', models.PositiveIntegerField()),
                ('final_grade', models.PositiveIntegerField()),
                ('subject', models.CharField(db_index=True, max_length=20)),
                ('G1_pct', models.FloatField()),
                ('G2_pct', models.FloatField()),
                ('final_grade_pct', models.FloatField(db_index=True)),
                ('attendance_pct', models.FloatField(db_index=True)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
    ]
